type Page {
    id: ID! @unique
    title: String!
    components: [PageComponent]
    pages: [PagePages]
    users: [User] @relation(name: "USER_PAGE", direction: IN)
    recipes: [Recipe] @relation(name: "RECIPE_PAGE", direction: IN)
}

type PageComponent @relation(name: "PAGE_COMPONENT") {
    from: Page
    to: Component
    index: Int!
}

type PagePages @relation(name: "PAGE_PAGE") {
    from: Page
    to: Page
    index: Int!
}
